# Generated by Django 4.2.3 on 2024-05-10 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
